apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pipeline-provenance-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pipeline-provenance-test
    app.kubernetes.io/part-of: pipeline-provenance-test
  name: pipeline-provenance-test
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: pipeline-provenance-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: pipeline-provenance-test
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/brianwcook-tenant/pipeline-provenance-test/pipeline-provenance-test@sha256:b92bf490ccce95a26f60a02e4b513f2873791c6667684608666c9c978e678c3a
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
