apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pipeline-provenance-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pipeline-provenance-test
    app.kubernetes.io/part-of: pipeline-provenance-test
  name: pipeline-provenance-test
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: pipeline-provenance-test
status:
  loadBalancer: {}
