apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: pipeline-provenance-test
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/brianwcook-tenant/pipeline-provenance-test/pipeline-provenance-test@sha256:b92bf490ccce95a26f60a02e4b513f2873791c6667684608666c9c978e678c3a
        name: my-python
        resources: {}
status: {}
